Imported upstream version '3.2.3' of 'upstream'

diff --git a/.github/workflows/reusable-windows-ci.yml b/.github/workflows/reusable-windows-ci.yml
--- a/.github/workflows/reusable-windows-ci.yml
+++ b/.github/workflows/reusable-windows-ci.yml
@@ -1,4 +1,4 @@
-name: Fast-DDS Windows CI reusable workflow
+name: Fast DDS Windows CI reusable workflow
 
 on:
   workflow_call:
@@ -27,25 +27,28 @@ on:
         description: 'Branch or tag of Fast CDR repository (https://github.com/eProsima/Fast-CDR)'
         required: false
         type: string
-        default: '2.2.x'
+        default: '2.3.x'
       cmake-config:
         description: 'CMake configuration to use'
         required: false
         type: string
         default: 'RelWithDebInfo'
+      run-tests:
+        description: 'Run test suite of Fast DDS'
+        required: false
+        type: boolean
+        default: true
 
 defaults:
   run:
     shell: pwsh
 
 jobs:
-  reusable-windows-ci:
+  fastdds_build:
     runs-on: windows-2022
     strategy:
       fail-fast: false
       matrix:
-        cmake-config:
-          - 'RelWithDebInfo'
         vs-toolset:
           - 'v142'
           - 'v143'
@@ -53,7 +56,7 @@ jobs:
       - name: Sync eProsima/Fast-DDS repository
         uses: eProsima/eProsima-CI/external/checkout@v0
         with:
-          path: src/fastrtps
+          path: src/fastdds
           submodules: true
           ref: ${{ inputs.fastdds_branch }}
 
@@ -99,10 +102,88 @@ jobs:
       - name: Install Python dependencies
         uses: eProsima/eProsima-CI/windows/install_python_packages@v0
         with:
-          packages: vcstool xmlschema
+          packages: vcstool xmlschema psutil
+
+      - name: Get Fast CDR branch
+        id: get_fastcdr_branch
+        uses: eProsima/eProsima-CI/ubuntu/get_related_branch_from_repo@v0
+        with:
+          remote_repository: eProsima/Fast-CDR
+          fallback_branch: ${{ inputs.fastcdr_branch }}
+
+      - name: Download Fast CDR
+        uses: eProsima/eProsima-CI/external/checkout@v0
+        with:
+          repository: eProsima/Fast-CDR
+          path: ${{ github.workspace }}/src/fastcdr
+          ref: ${{ steps.get_fastcdr_branch.outputs.deduced_branch }}
+
+      - name: Fetch Fast DDS dependencies
+        uses: eProsima/eProsima-CI/multiplatform/vcs_import@v0
+        with:
+          vcs_repos_file: ${{ github.workspace }}\src\fastdds\fastdds.repos
+          destination_workspace: src
+          skip_existing: 'true'
+
+      - name: Fetch Fast DDS CI dependencies
+        uses: eProsima/eProsima-CI/multiplatform/vcs_import@v0
+        with:
+          vcs_repos_file: ${{ github.workspace }}\src\fastdds\.github\workflows\config\fastdds_test.repos
+          destination_workspace: src
+          skip_existing: 'true'
+
+      - name: Build
+        id: build
+        continue-on-error: false
+        uses: eProsima/eProsima-CI/windows/colcon_build@v0
+        with:
+          colcon_meta_file: ${{ github.workspace }}\src\fastdds\.github\workflows\config\fastdds_build.meta ${{ github.workspace }}\src\fastdds\.github\workflows\config\fastdds_test.meta
+          colcon_build_args: ${{ inputs.colcon-args }}
+          # The following Fast DDS CMake options need to be specified here instead of in the meta files
+          # because they vary from platform to platform
+          cmake_args_default: ${{ inputs.cmake-args }} -T ${{ matrix.vs-toolset }} -DTHIRDPARTY_Asio=FORCE -DTHIRDPARTY_TinyXML2=FORCE -DTHIRDPARTY_fastcdr=OFF -DTHIRDPARTY_UPDATE=ON -DCOMPILE_EXAMPLES=ON -DEPROSIMA_EXTRA_CMAKE_CXX_FLAGS="/MP /WX"
+          cmake_build_type: ${{ inputs.cmake-config }}
+          workspace: ${{ github.workspace }}
+
+      - name: Upload build artifacts
+        uses: eProsima/eProsima-CI/external/upload-artifact@v0
+        with:
+          name: fastdds_build_${{ inputs.label }}_${{ matrix.vs-toolset }}
+          path: ${{ github.workspace }}
+
+  fastdds_test:
+    needs: fastdds_build
+    if: ${{ inputs.run-tests == true }}
+    name: fastdds_test (${{ matrix.cmake_build_type }}, ${{ matrix.test_filter }}), ${{ matrix.vs-toolset }}
+    runs-on: windows-2022
+    strategy:
+      fail-fast: false
+      matrix:
+        vs-toolset:
+          - 'v142'
+          - 'v143'
+        cmake_build_type:
+          - ${{ inputs.cmake-config }}
+        test_filter:
+          - 'blackbox'
+          - 'unittest-I'
+          - 'unittest-II'
+          - 'examples'
+        filter_expression_blackbox:
+          - 'BlackboxTests|ParticipantTests|SecureDiscoverServer|SimpleCommunication|system.'
+        filter_expression_examples:
+          - 'example_tests'
+        filter_expression_unittests_I:
+          - 'DDSSQLFilterValue'
+
+    steps:
+      - name: Download build artifacts
+        uses: eProsima/eProsima-CI/external/download-artifact@v0
+        with:
+          name: fastdds_build_${{ inputs.label }}_${{ matrix.vs-toolset }}
+          path: ${{ github.workspace }}
 
       - name: Update known hosts file for DNS resolver testing
-        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-test') }}
         run: |
           $hostfile = "$Env:SystemRoot\system32\drivers" -replace "\\", "/"
           $hostfile += "/etc/hosts"
@@ -129,63 +210,84 @@ jobs:
           # Show the result
           gc $hostfile
 
-      - name: Get Fast CDR branch
-        id: get_fastcdr_branch
-        uses: eProsima/eProsima-CI/ubuntu/get_related_branch_from_repo@v0
+      - name: Install Fix Python version
+        uses: eProsima/eProsima-CI/external/setup-python@v0
         with:
-          remote_repository: eProsima/Fast-CDR
-          fallback_branch: ${{ inputs.fastcdr_branch }}
+          python-version: '3.11'
 
-      - name: Download Fast CDR
-        uses: eProsima/eProsima-CI/external/checkout@v0
+      - name: Get minimum supported version of CMake
+        uses: eProsima/eProsima-CI/external/get-cmake@v0
         with:
-          repository: eProsima/Fast-CDR
-          path: ${{ github.workspace }}/src/fastcdr
-          ref: ${{ steps.get_fastcdr_branch.outputs.deduced_branch }}
+          cmakeVersion: '3.22.6'
 
-      - name: Fetch Fast DDS dependencies
-        uses: eProsima/eProsima-CI/multiplatform/vcs_import@v0
+      - name: Install OpenSSL
+        uses: eProsima/eprosima-CI/windows/install_openssl@v0
         with:
-          vcs_repos_file: ${{ github.workspace }}\src\fastrtps\fastrtps.repos
-          destination_workspace: src
-          skip_existing: 'true'
+          version: '3.1.1'
 
-      - name: Fetch Fast DDS CI dependencies
-        uses: eProsima/eProsima-CI/multiplatform/vcs_import@v0
+      - name: Update OpenSSL environment variables
+        run: |
+          # Update the environment
+          if (Test-Path -Path $Env:ProgramW6432\OpenSSL)
+          {
+            "OPENSSL64_ROOT=$Env:ProgramW6432\OpenSSL" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
+          }
+          elseif (Test-Path -Path $Env:ProgramW6432\OpenSSL-Win)
+          {
+            "OPENSSL64_ROOT=$Env:ProgramW6432\OpenSSL-Win" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
+          }
+          elseif (Test-Path -Path $Env:ProgramW6432\OpenSSL-Win64)
+          {
+            "OPENSSL64_ROOT=$Env:ProgramW6432\OpenSSL-Win64" | Out-File $Env:GITHUB_ENV -Append -Encoding OEM
+          }
+          else
+          {
+            Write-Error -Message "Cannot find OpenSSL installation."
+            exit 1
+          }
+
+      - name: Install colcon
+        uses: eProsima/eProsima-CI/windows/install_colcon@v0
+
+      - name: Install Python dependencies
+        uses: eProsima/eProsima-CI/windows/install_python_packages@v0
         with:
-          vcs_repos_file: ${{ github.workspace }}\src\fastrtps\.github\workflows\config\fastdds_test.repos
-          destination_workspace: src
-          skip_existing: 'true'
+          packages: vcstool xmlschema psutil
 
-      - name: Build
-        id: build
+      #Build Windows examples testing docker image
+      - name: Build with example testing
+        if: ${{ matrix.test_filter == 'examples' }}
         continue-on-error: false
         uses: eProsima/eProsima-CI/windows/colcon_build@v0
         with:
-          colcon_meta_file: ${{ github.workspace }}\src\fastrtps\.github\workflows\config\fastdds_build.meta ${{ github.workspace }}\src\fastrtps\.github\workflows\config\fastdds_test.meta
+          colcon_meta_file: ${{ github.workspace }}\src\fastdds\.github\workflows\config\fastdds_build.meta ${{ github.workspace }}\src\fastdds\.github\workflows\config\fastdds_test.meta
           colcon_build_args: ${{ inputs.colcon-args }}
           # The following Fast DDS CMake options need to be specified here instead of in the meta files
           # because they vary from platform to platform
-          cmake_args_default: ${{ inputs.cmake-args }} -T ${{ matrix.vs-toolset }} -DTHIRDPARTY_Asio=FORCE -DTHIRDPARTY_TinyXML2=FORCE -DTHIRDPARTY_fastcdr=OFF -DTHIRDPARTY_UPDATE=ON -DEPROSIMA_EXTRA_CMAKE_CXX_FLAGS="/MP /WX"
-          cmake_build_type: ${{ matrix.cmake-config }}
+          cmake_args_default: ${{ inputs.cmake-args }} -T ${{ matrix.vs-toolset }} -DTHIRDPARTY_Asio=FORCE -DTHIRDPARTY_TinyXML2=FORCE -DTHIRDPARTY_fastcdr=OFF -DTHIRDPARTY_UPDATE=ON -DFASTDDS_EXAMPLE_TESTS=ON -DEPROSIMA_EXTRA_CMAKE_CXX_FLAGS="/MP /WX"
+          cmake_build_type: ${{ inputs.cmake-config }}
           workspace: ${{ github.workspace }}
 
       - name: Test
-        if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-test') }}
         id: test
         uses: eProsima/eProsima-CI/windows/colcon_test@v0
         with:
-          colcon_meta_file: ${{ github.workspace }}\src\fastrtps\.github\workflows\config\fastdds_test.meta
+          colcon_meta_file: ${{ github.workspace }}\src\fastdds\.github\workflows\config\fastdds_test.meta
           colcon_test_args: ${{ inputs.colcon-args }}
           colcon_test_args_default: --event-handlers=console_direct+
-          ctest_args: ${{ inputs.ctest-args }}
-          packages_names: fastrtps
+          ctest_args: >
+            ${{ inputs.ctest-args }}
+            ${{ matrix.test_filter == 'blackbox' && format('-R "{0}"', matrix.filter_expression_blackbox) ||
+                matrix.test_filter == 'examples' && format('-R "{0}"', matrix.filter_expression_examples) ||
+                matrix.test_filter == 'unittest-I' && format('-R "{0}" -j 4', matrix.filter_expression_unittests_I) ||
+                format('-E "{0}|{1}|{2}"', matrix.filter_expression_blackbox, matrix.filter_expression_examples, matrix.filter_expression_unittests_I) }}
+          packages_names: fastdds
           workspace: ${{ github.workspace }}
           test_report_artifact: ${{ format('test_report_{0}_{1}_{2}', inputs.label, github.job, join(matrix.*, '_')) }}
 
       - name: Test summary
         uses: eProsima/eProsima-CI/windows/junit_summary@v0
-        if: ${{ !cancelled() && !contains(github.event.pull_request.labels.*.name, 'no-test') }}
+        if: ${{ !cancelled() }}
         with:
           junit_reports_dir: "${{ steps.test.outputs.ctest_results_path }}"
           print_summary: 'True'
